{{- if .Values.gateway.nginxGateway -}}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "myapp.fullname" . }}-gateway
  labels:
    {{- include "myapp.labels" . | nindent 4}}
    app.kubernetes.io/name: myapp
    app.kubernetes.io/component: gateway
spec:
  gatewayClassName: {{ .Values.gateway.gatewayClassName }}

  listeners:
    - name: {{ .Values.gateway.listeners.name }}
      port: {{ .Values.gateway.listeners.port }}
      protocol: {{ .Values.gateway.listeners.protocol }}
{{- end }}