nameOverride: ""
fullnameOverride: "myapp"

frontend:
  replicaCount: 1
  
  image:
    repository: pdevfig/front-temp
    tag: 0.1.1
    pullPolicy: IfNotPresent
  
  service:
    type: ClusterIP
    port: 80
    targetPort: http

  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi
  
  probes:
    startup:
      path: /
      periodSeconds: 5
      timeoutSeconds: 2
      failureThreshold: 30
  
    readiness:
      path: /
      periodSeconds: 20
      timeoutSeconds: 2
      failureThreshold: 3
    
    liveness:
      path: /
      periodSeconds: 10
      timeoutSeconds: 2
      failureThreshold: 2
    
  securityContext:
    runAsNonRoot: false
  
backend:
  replicaCount: 1
  
  image:
    repository: pdevfig/temp-api-dhi
    tag: 0.1.2
    pullPolicy: IfNotPresent
  
  service:
    type: ClusterIP
    port: 9000
    targetPort: 9000

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  
  probes:
    startup:
      path: /healthz
      periodSeconds: 5
      timeoutSeconds: 2
      failureThreshold: 30
    
    readiness:
      path: /healthz
      periodSeconds: 10
      timeoutSeconds: 2
      failureThreshold: 3
     
    liveness:
      path: /healthz
      periodSeconds: 20
      timeoutSeconds: 2
      failureThreshold: 3
    
  securityContext:
    runAsNonRoot: false

# security context
securityContext:
  pod:
    seccompProfile:
      type: RuntimeDefault
  
  container:
    allowPrivilegeEscalation: false
    capabilties:
      drop: 
        - ALL
  
# gateway related
gateway:
  # true wheather nginx gateway is present
  nginxGateway: true 
  gatewayClassName: nginx
  listeners:
    name: http
    protocol: HTTP
    port: 80
  
httpRoute:
  rules:
    backend:
      path:
        pathType: PathPrefix
        value: /api
      filter:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
    frontend:
      path:
        pathType: PathPrefix
        value: /