name: test-dispatch
on:
  workflow_dispatch:
    inputs:
      number:
        required: true
        type: number
      

jobs:
  print-to-summary:
    runs-on: ubuntu-latest
    steps:
      - name: echo to github step summary
        run: |
          cat << EOF >> $GITHUB_STEP_SUMMARY
          Preview environment 
          Preview: https://pr-${{ inputs.number }}.myapp.example.com
          EOF
      - name: echo with clikable
        run: |
          cat << EOF >> $GITHUB_STEP_SUMMARY
          The url is:
          [Open Preview](Preview: https://pr-${{ inputs.number }}.myapp.example.com)
          EOF
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Web UI Summary
        run: |
          cat << 'EOF' >> $GITHUB_STEP_SUMMARY
          ### 🚀 Deployment Status
          The build was successful!
          
          - **Version:** 1.2.0
          - **Environment:** Production
          
          | Metric | Value | Status |
          | --- | --- | --- |
          | Code Coverage | 92% | ✅ |
          | Bundled Size | 1.4 MB | ⚠️ |
          EOF

